### ISSUE TITLE
gtf file in 'mo' mode

### ISSUE THREAD

**Issue by RAWWiberg** [FemeniasM/ExplorATE_shell_script#2]
Hello, 

I am wondering why the .gtf/.gff file for the genome is a mandatory argument when running in 'mo' mode. It does not seem as if it is used in the shell script. Am I missing something?

**Comment by FemeniasM** [comment]
Dear @RAWWiberg,
Thank you very much for using ExplorATE and for your comment. Your observation is correct. The .gtf/.gff file was mandatory in the first version of the script since it discriminated between genetic and intergenic regions. The current version takes all the fragments identified in the RepeatMasker file to create the reference, however I hope to add the option to include repeats within gene regions as decoy sequences soon. This way users will be able to optionally use this argument (unlike the first version) to decide whether to include repeats in gene regions as decoys or, if it makes sense for further analysis, include them in the reference. The output file provides details of the region in question that is being quantified, so overlapping repeats with genes can be easily identified.
am attentive to any comment or suggestion, 
best regards

**Comment by RAWWiberg** [comment]
Dear @FemeniasM , 
Thanks very much for the clarification. I just wanted to make sure I understood what was going on :).
I'll close this issue.
Best regards,
